### ISSUE TITLE
[TODO] is there anything similar for lldb?

### ISSUE THREAD

**Issue by timotheecour** [cooldome/Nim-gdb#3]

**Comment by krux02** [comment]
nope, but you can create ``nim-lldb`` analog to [``nim-gdb``](https://github.com/nim-lang/Nim/blob/devel/bin/nim-gdb) and port [``nim-gdb.py``](https://github.com/nim-lang/Nim/blob/devel/tools/nim-gdb.py) over for lldb.

This [this lldb rust formatter](https://github.com/rust-lang/rust/blob/master/src/etc/lldb_rust_formatters.py) might be a good example to teach you everything that is necessary.  And please make it as a pull request for Nim when it works.

**Comment by krux02** [comment]
Can you close this issue? This is clearly just a question not an issue of this project at all.
